version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - 'geoip/**'

nfpms:
  - id: network-checker
    description: CLI-utility to check Kontur services availability
    vendor: SKB Kontur
    homepage: https://github.com/skbkontur/network-checker
    maintainer: e.juravlev@skbkontur.ru
    license: GPL
    formats: [deb, rpm]
    contents:
      - src: './geoip/'
        dst: '/usr/local/lib/geoip'
